#!/bin/bash
cd /home/h.noorazar/rangeland_bio/01_rolling_variance/

####for y_ in avg_of_dailyAvgTemp_C temp_detrendLinReg temp_detrendDiff temp_detrendSens precip_mm prec_detrendLinReg prec_detrendDiff prec_detrendSens
for y_ in avg_of_dailyAvgTemp_C \
          max_of_monthlyAvg_of_dailyMaxTemp_C \
          min_of_monthlyAvg_of_dailyMinTemp_C \
          avg_of_monthlymax_of_dailyMaxTemp_C \
          avg_of_monthlymin_of_dailyMinTemp_C \
          avg_of_dailyAvgTemp_C_detrendSens \
          avg_of_monthlymax_of_dailyMaxTemp_C_detrendSens \
          avg_of_monthlymin_of_dailyMinTemp_C_detrendSens \
          max_of_monthlyAvg_of_dailyMaxTemp_C_detrendSens \
          min_of_monthlyAvg_of_dailyMinTemp_C_detrendSens \
          avg_of_dailyAvgTemp_C_detrendLinReg \
          avg_of_monthlymax_of_dailyMaxTemp_C_detrendLinReg \
          avg_of_monthlymin_of_dailyMinTemp_C_detrendLinReg \
          max_of_monthlyAvg_of_dailyMaxTemp_C_detrendLinReg \
          min_of_monthlyAvg_of_dailyMinTemp_C_detrendLinReg \
          precip_mm \
          precip_mm_detrendLinReg \
          precip_mm_detrendSens \
          thi_avg \
          thi_avg_detrendSens \
          thi_avg_detrendLinReg \
          avg_of_dailyAvg_rel_hum \
          avg_of_dailyAvg_rel_hum_detrendSens \
          avg_of_dailyAvg_rel_hum_detrendLinReg\
          et0_Apr\
          et0_Apr_detrendLinReg\
          et0_Apr_detrendSens\
          et0_Aug\
          et0_Aug_detrendLinReg\
          et0_Aug_detrendSens\
          et0_Dec\
          et0_Dec_detrendLinReg\
          et0_Dec_detrendSens\
          et0_Feb\
           et0_Feb_detrendLinReg\
           et0_Feb_detrendSens\
           et0_Jan\
           et0_Jan_detrendLinReg\
           et0_Jan_detrendSens\
           et0_Jul\
           et0_Jul_detrendLinReg\
           et0_Jul_detrendSens\
           et0_Jun\
           et0_Jun_detrendLinReg\
           et0_Jun_detrendSens\
           et0_Mar\
           et0_Mar_detrendLinReg\
           et0_Mar_detrendSens\
           et0_May\
           et0_May_detrendLinReg\
           et0_May_detrendSens\
           et0_Nov\
           et0_Nov_detrendLinReg\
           et0_Nov_detrendSens\
           et0_Oct\
           et0_Oct_detrendLinReg\
           et0_Oct_detrendSens\
           et0_Sep\
           et0_Sep_detrendLinReg\
           et0_Sep_detrendSens\
           et0_annualSum\
           et0_annualSum_detrendLinReg\
           et0_annualSum_detrendSens\
           etr_Apr\
           etr_Apr_detrendLinReg\
           etr_Apr_detrendSens\
           etr_Aug\
           etr_Aug_detrendLinReg\
           etr_Aug_detrendSens\
           etr_Dec\
           etr_Dec_detrendLinReg\
           etr_Dec_detrendSens\
           etr_Feb\
           etr_Feb_detrendLinReg\
           etr_Feb_detrendSens\
           etr_Jan\
           etr_Jan_detrendLinReg\
           etr_Jan_detrendSens\
           etr_Jul\
           etr_Jul_detrendLinReg\
           etr_Jul_detrendSens\
           etr_Jun\
           etr_Jun_detrendLinReg\
           etr_Jun_detrendSens\
           etr_Mar\
           etr_Mar_detrendLinReg\
           etr_Mar_detrendSens\
           etr_May\
           etr_May_detrendLinReg\
           etr_May_detrendSens\
           etr_Nov\
           etr_Nov_detrendLinReg\
           etr_Nov_detrendSens\
           etr_Oct\
           etr_Oct_detrendLinReg\
           etr_Oct_detrendSens\
           etr_Sep\
           etr_Sep_detrendLinReg\
           etr_Sep_detrendSens\
           etr_annualSum\
           etr_annualSum_detrendLinReg\
           etr_annualSum_detrendSens\
           spei_12mon_Apr\
           spei_12mon_Apr_detrendLinReg\
           spei_12mon_Apr_detrendSens\
           spei_12mon_Aug\
           spei_12mon_Aug_detrendLinReg\
           spei_12mon_Aug_detrendSens\
           spei_12mon_Dec\
           spei_12mon_Dec_detrendLinReg\
           spei_12mon_Dec_detrendSens\
           spei_12mon_Feb\
           spei_12mon_Feb_detrendLinReg\
           spei_12mon_Feb_detrendSens\
           spei_12mon_Jan\
           spei_12mon_Jan_detrendLinReg\
           spei_12mon_Jan_detrendSens\
           spei_12mon_Jul\
           spei_12mon_Jul_detrendLinReg\
           spei_12mon_Jul_detrendSens\
           spei_12mon_Jun\
           spei_12mon_Jun_detrendLinReg\
           spei_12mon_Jun_detrendSens\
           spei_12mon_Mar\
           spei_12mon_Mar_detrendLinReg\
           spei_12mon_Mar_detrendSens\
           spei_12mon_May\
           spei_12mon_May_detrendLinReg\
           spei_12mon_May_detrendSens\
           spei_12mon_Nov\
           spei_12mon_Nov_detrendLinReg\
           spei_12mon_Nov_detrendSens\
           spei_12mon_Oct\
           spei_12mon_Oct_detrendLinReg\
           spei_12mon_Oct_detrendSens\
           spei_12mon_Sep\
           spei_12mon_Sep_detrendLinReg\
           spei_12mon_Sep_detrendSens\
           spei_1mon_Apr\
           spei_1mon_Apr_detrendLinReg\
           spei_1mon_Apr_detrendSens\
           spei_1mon_Aug\
           spei_1mon_Aug_detrendLinReg\
           spei_1mon_Aug_detrendSens\
           spei_1mon_Dec\
           spei_1mon_Dec_detrendLinReg\
           spei_1mon_Dec_detrendSens\
           spei_1mon_Feb\
           spei_1mon_Feb_detrendLinReg\
           spei_1mon_Feb_detrendSens\
           spei_1mon_Jan\
           spei_1mon_Jan_detrendLinReg\
           spei_1mon_Jan_detrendSens\
           spei_1mon_Jul\
           spei_1mon_Jul_detrendLinReg\
           spei_1mon_Jul_detrendSens\
           spei_1mon_Jun\
           spei_1mon_Jun_detrendLinReg\
           spei_1mon_Jun_detrendSens\
           spei_1mon_Mar\
           spei_1mon_Mar_detrendLinReg\
           spei_1mon_Mar_detrendSens\
           spei_1mon_May\
           spei_1mon_May_detrendLinReg\
           spei_1mon_May_detrendSens\
           spei_1mon_Nov\
           spei_1mon_Nov_detrendLinReg\
           spei_1mon_Nov_detrendSens\
           spei_1mon_Oct\
           spei_1mon_Oct_detrendLinReg\
           spei_1mon_Oct_detrendSens\
           spei_1mon_Sep\
           spei_1mon_Sep_detrendLinReg\
           spei_1mon_Sep_detrendSens\
           spei_24mon_Apr\
           spei_24mon_Apr_detrendLinReg\
           spei_24mon_Apr_detrendSens\
           spei_24mon_Aug\
           spei_24mon_Aug_detrendLinReg\
           spei_24mon_Aug_detrendSens\
           spei_24mon_Dec\
           spei_24mon_Dec_detrendLinReg\
           spei_24mon_Dec_detrendSens\
           spei_24mon_Feb\
           spei_24mon_Feb_detrendLinReg\
           spei_24mon_Feb_detrendSens\
           spei_24mon_Jan\
           spei_24mon_Jan_detrendLinReg\
           spei_24mon_Jan_detrendSens\
           spei_24mon_Jul\
           spei_24mon_Jul_detrendLinReg\
           spei_24mon_Jul_detrendSens\
           spei_24mon_Jun\
           spei_24mon_Jun_detrendLinReg\
           spei_24mon_Jun_detrendSens\
           spei_24mon_Mar\
           spei_24mon_Mar_detrendLinReg\
           spei_24mon_Mar_detrendSens\
           spei_24mon_May\
           spei_24mon_May_detrendLinReg\
           spei_24mon_May_detrendSens\
           spei_24mon_Nov\
           spei_24mon_Nov_detrendLinReg\
           spei_24mon_Nov_detrendSens\
           spei_24mon_Oct\
           spei_24mon_Oct_detrendLinReg\
           spei_24mon_Oct_detrendSens\
           spei_24mon_Sep\
           spei_24mon_Sep_detrendLinReg\
           spei_24mon_Sep_detrendSens\
           spei_2mon_Apr\
           spei_2mon_Apr_detrendLinReg\
           spei_2mon_Apr_detrendSens\
           spei_2mon_Aug\
           spei_2mon_Aug_detrendLinReg\
           spei_2mon_Aug_detrendSens\
           spei_2mon_Dec\
           spei_2mon_Dec_detrendLinReg\
           spei_2mon_Dec_detrendSens\
           spei_2mon_Feb\
           spei_2mon_Feb_detrendLinReg\
           spei_2mon_Feb_detrendSens\
           spei_2mon_Jan\
           spei_2mon_Jan_detrendLinReg\
           spei_2mon_Jan_detrendSens\
           spei_2mon_Jul\
           spei_2mon_Jul_detrendLinReg\
           spei_2mon_Jul_detrendSens\
           spei_2mon_Jun\
           spei_2mon_Jun_detrendLinReg\
           spei_2mon_Jun_detrendSens\
           spei_2mon_Mar\
           spei_2mon_Mar_detrendLinReg\
           spei_2mon_Mar_detrendSens\
           spei_2mon_May\
           spei_2mon_May_detrendLinReg\
           spei_2mon_May_detrendSens\
           spei_2mon_Nov\
           spei_2mon_Nov_detrendLinReg\
           spei_2mon_Nov_detrendSens\
           spei_2mon_Oct\
           spei_2mon_Oct_detrendLinReg\
           spei_2mon_Oct_detrendSens\
           spei_2mon_Sep\
           spei_2mon_Sep_detrendLinReg\
           spei_2mon_Sep_detrendSens\
           spei_3mon_Apr\
           spei_3mon_Apr_detrendLinReg\
           spei_3mon_Apr_detrendSens\
           spei_3mon_Aug\
           spei_3mon_Aug_detrendLinReg\
           spei_3mon_Aug_detrendSens\
           spei_3mon_Dec\
           spei_3mon_Dec_detrendLinReg\
           spei_3mon_Dec_detrendSens\
           spei_3mon_Feb\
           spei_3mon_Feb_detrendLinReg\
           spei_3mon_Feb_detrendSens\
           spei_3mon_Jan\
           spei_3mon_Jan_detrendLinReg\
           spei_3mon_Jan_detrendSens\
           spei_3mon_Jul\
           spei_3mon_Jul_detrendLinReg\
           spei_3mon_Jul_detrendSens\
           spei_3mon_Jun\
           spei_3mon_Jun_detrendLinReg\
           spei_3mon_Jun_detrendSens\
           spei_3mon_Mar\
           spei_3mon_Mar_detrendLinReg\
           spei_3mon_Mar_detrendSens\
           spei_3mon_May\
           spei_3mon_May_detrendLinReg\
           spei_3mon_May_detrendSens\
           spei_3mon_Nov\
           spei_3mon_Nov_detrendLinReg\
           spei_3mon_Nov_detrendSens\
           spei_3mon_Oct\
           spei_3mon_Oct_detrendLinReg\
           spei_3mon_Oct_detrendSens\
           spei_3mon_Sep\
           spei_3mon_Sep_detrendLinReg\
           spei_3mon_Sep_detrendSens\
           spei_6mon_Apr\
           spei_6mon_Apr_detrendLinReg\
           spei_6mon_Apr_detrendSens\
           spei_6mon_Aug\
           spei_6mon_Aug_detrendLinReg\
           spei_6mon_Aug_detrendSens\
           spei_6mon_Dec\
           spei_6mon_Dec_detrendLinReg\
           spei_6mon_Dec_detrendSens\
           spei_6mon_Feb\
           spei_6mon_Feb_detrendLinReg\
           spei_6mon_Feb_detrendSens\
           spei_6mon_Jan\
           spei_6mon_Jan_detrendLinReg\
           spei_6mon_Jan_detrendSens\
           spei_6mon_Jul\
           spei_6mon_Jul_detrendLinReg\
           spei_6mon_Jul_detrendSens\
           spei_6mon_Jun\
           spei_6mon_Jun_detrendLinReg\
           spei_6mon_Jun_detrendSens\
           spei_6mon_Mar\
           spei_6mon_Mar_detrendLinReg\
           spei_6mon_Mar_detrendSens\
           spei_6mon_May\
           spei_6mon_May_detrendLinReg\
           spei_6mon_May_detrendSens\
           spei_6mon_Nov\
           spei_6mon_Nov_detrendLinReg\
           spei_6mon_Nov_detrendSens\
           spei_6mon_Oct\
           spei_6mon_Oct_detrendLinReg\
           spei_6mon_Oct_detrendSens\
           spei_6mon_Sep\
           spei_6mon_Sep_detrendLinReg\
           spei_6mon_Sep_detrendSens\
           spei_9mon_Apr\
           spei_9mon_Apr_detrendLinReg\
           spei_9mon_Apr_detrendSens\
           spei_9mon_Aug\
           spei_9mon_Aug_detrendLinReg\
           spei_9mon_Aug_detrendSens\
           spei_9mon_Dec\
           spei_9mon_Dec_detrendLinReg\
           spei_9mon_Dec_detrendSens\
           spei_9mon_Feb\
           spei_9mon_Feb_detrendLinReg\
           spei_9mon_Feb_detrendSens\
           spei_9mon_Jan\
           spei_9mon_Jan_detrendLinReg\
           spei_9mon_Jan_detrendSens\
           spei_9mon_Jul\
           spei_9mon_Jul_detrendLinReg\
           spei_9mon_Jul_detrendSens\
           spei_9mon_Jun\
           spei_9mon_Jun_detrendLinReg\
           spei_9mon_Jun_detrendSens\
           spei_9mon_Mar\
           spei_9mon_Mar_detrendLinReg\
           spei_9mon_Mar_detrendSens\
           spei_9mon_May\
           spei_9mon_May_detrendLinReg\
           spei_9mon_May_detrendSens\
           spei_9mon_Nov\
           spei_9mon_Nov_detrendLinReg\
           spei_9mon_Nov_detrendSens\
           spei_9mon_Oct\
           spei_9mon_Oct_detrendLinReg\
           spei_9mon_Oct_detrendSens\
           spei_9mon_Sep\
           spei_9mon_Sep_detrendLinReg\
           spei_9mon_Sep_detrendSens
do
  for window_size in 5 6 7 8 9 10
  do
    cp weather_variance_rolling_temp.sh   ./qsubs/weather_variance_rolling_$window_size$y_.sh
    sed -i s/window_size/"$window_size"/g ./qsubs/weather_variance_rolling_$window_size$y_.sh
    sed -i s/y_/"$y_"/g                   ./qsubs/weather_variance_rolling_$window_size$y_.sh
  done
done